name: CI / CD frontend in Docker
on:
  push:
    branches:
      - 5-CICD-SpecFlow-LivingDoc
    paths:
      - 'FRONT/**'
      - '.github/workflows/workflow-frontend.yaml'

defaults:
  run:
    working-directory: ./FRONT/APP.Web/vaultapp

jobs:
  front-angular:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3

      - name: Build all projects
        run: |
          npm install -g @angular/cli
          npm install
          ng build
